### ISSUE TITLE
No se me ha actualizado login/no me aparece la nueva rama que creaste tampoco. 

### ISSUE THREAD

**Issue by milv24** [djose1164/Programacion-Modular#15]
![image](https://user-images.githubusercontent.com/79891120/114126742-01bcdb00-98c7-11eb-9249-b290ac370d18.png)
![image](https://user-images.githubusercontent.com/79891120/114126761-0e413380-98c7-11eb-8a2c-f7814b129367.png)

**Comment by milv24** [comment]
@djose1164

**Comment by djose1164** [comment]
Hmm, tu repo esta bien atrasado. Intentaste hacer git pull origin main desde la terminal? Intentalo y muestrame el output.

**Comment by djose1164** [comment]
> Hmm, tu repo esta bien atrasado. Intentaste hacer git pull origin main desde la terminal? Intentalo y muestrame el output.

Ahh, olvidalo. Estas desde venta. Primero debes cambiar tu rama dale click a Ventas y elige login-improved.

**Comment by djose1164** [comment]
Si no te aparece login-improved corre el siguiente comando en la terminal `git clone --single-branch --branch login-improved https://github.com/djose1164/Programacion-Modular.git`

**Comment by milv24** [comment]
![image](https://user-images.githubusercontent.com/79891120/114128273-01720f00-98ca-11eb-8c78-601ee832acef.png)
Eso me aparece en la terminal luego de darle

**Comment by milv24** [comment]
![image](https://user-images.githubusercontent.com/79891120/114128451-5f9ef200-98ca-11eb-9e49-db56f33b7b66.png)
@djose1164

**Comment by djose1164** [comment]
> ![image](https://user-images.githubusercontent.com/79891120/114128451-5f9ef200-98ca-11eb-9e49-db56f33b7b66.png)
> @djose1164

Hmm parece que no pusiste el link del repo? Pero trata esto `git checkout origin/login-improved && git checkout -b login-improved && git push --set-upstream origin login-improved`. Eso deberia funcionar, cualquier error muestramelo, si funciona cierra el issue comentado q funciono.

**Comment by milv24** [comment]
Me dice que no es compatible esto "&&"

**Comment by milv24** [comment]
![image](https://user-images.githubusercontent.com/79891120/114129839-5cf1cc00-98cd-11eb-833b-b19318dc16d6.png)

**Comment by djose1164** [comment]
Quitalos. Es decir, dividelos en varios comandos, uno primero y despue otro clickeando enter.

**Comment by djose1164** [comment]
> Me dice que no es compatible esto "&&"

Y al parecer eso no funciona en Windows jajaja

**Comment by djose1164** [comment]
> ![image](https://user-images.githubusercontent.com/79891120/114129839-5cf1cc00-98cd-11eb-833b-b19318dc16d6.png)

@milv24 Lo estoy viendo mas en detalle y q version de git tenes? `git --version` muestrame su output.

**Comment by milv24** [comment]
git version 2.31.1.windows.1

**Comment by djose1164** [comment]
Estas al dia ciertamente

**Comment by milv24** [comment]
Resueltoooooo!!!!

**Comment by djose1164** [comment]
> Quitalos. Es decir, dividelos en varios comandos, uno primero y despue otro clickeando enter.

Te funciono?
