### ISSUE TITLE
Arreglo que hay que hacer en login

### ISSUE THREAD

**Issue by milv24** [djose1164/Programacion-Modular#17]
Primero, ya le di cambio a los colores, creo que debes aceptarlo para yo actualizar.

> Heyyy, debes eligir una opcion correcta!!!
> Porque, pues te quedan 2 intentos. 
Esto sale antes de que lo haya intentado el user

**Comment by djose1164** [comment]
Ahh, ok. No estoy muy al pendiente hoy jajaja xD

**Comment by djose1164** [comment]
> > Heyyy, debes eligir una opcion correcta!!!
> > Porque, pues te quedan 2 intentos.
> > Esto sale antes de que lo haya intentado el user

Como asi? Puedes dar mas contexto?

**Comment by djose1164** [comment]
Eso imprime el programa?

**Comment by djose1164** [comment]
> Primero, ya le di cambio a los colores, creo que debes aceptarlo para yo actualizar.

No veo ninguna Pull request. Tal vez es q tenes problemas de nuevo para el push?

**Comment by milv24** [comment]
> > > Heyyy, debes eligir una opcion correcta!!!
> > > Porque, pues te quedan 2 intentos.
> > > Esto sale antes de que lo haya intentado el user
> 
> Como asi? Puedes dar mas contexto?

Eso es lo que imrprime el programa, antes de que el usuario siquiera lo haya intentado.

**Comment by milv24** [comment]
> Eso imprime el programa?

Sip, exacto

**Comment by milv24** [comment]
> > Primero, ya le di cambio a los colores, creo que debes aceptarlo para yo actualizar.
> 
> No veo ninguna Pull request. Tal vez es q tenes problemas de nuevo para el push?

De seguro, porque Engeers hasta me dijo que lo pusiera gris el fondo y asi, pero parece que no se actualizaba.

**Comment by djose1164** [comment]
> > > > Heyyy, debes eligir una opcion correcta!!!
> > > > Porque, pues te quedan 2 intentos.
> > > > Esto sale antes de que lo haya intentado el user
> > 
> > 
> > Como asi? Puedes dar mas contexto?
> 
> Eso es lo que imrprime el programa, antes de que el usuario siquiera lo haya intentado.

Ahhh, ese bug. Yo ya habia hecho un bugfix. Puedes mostrarme tu archivo? De seguro que esta desactualizado.

**Comment by djose1164** [comment]
> De seguro, porque Engeers hasta me dijo que lo pusiera gris el fondo y asi, pero parece que no se actualizaba.

Verificaste que hiciste commit primero?

**Comment by djose1164** [comment]
He integrado la ultima version del login en main. Deberias intentar actualizar tu repo e intentar copilar de nuevo.

**Comment by milv24** [comment]
> > De seguro, porque Engeers hasta me dijo que lo pusiera gris el fondo y asi, pero parece que no se actualizaba.
> 
> Verificaste que hiciste commit primero?

Sip

**Comment by milv24** [comment]
> He integrado la ultima version del login en main. Deberias intentar actualizar tu repo e intentar copilar de nuevo.

Dejame intentar

**Comment by milv24** [comment]
Lo hago desde la rama de login. login-improved o desde ventas?

**Comment by milv24** [comment]
Lo hice desde ventas y no funciono

**Comment by djose1164** [comment]
> Lo hago desde la rama de login. login-improved o desde ventas?

No, desde main. `git pull origin main --force`

**Comment by djose1164** [comment]
> > > De seguro, porque Engeers hasta me dijo que lo pusiera gris el fondo y asi, pero parece que no se actualizaba.
> > 
> > 
> > Verificaste que hiciste commit primero?
> 
> Sip

Usa: `git checkout login && git merge login-improved && git push origin login`

**Comment by djose1164** [comment]
> Lo hice desde ventas y no funciono

Yo no he hecho ningun cambio alli xD

**Comment by milv24** [comment]
Le di a compilar y me siguen saliendo los mismos errores y el color, parece que no se me actualizo bien

**Comment by milv24** [comment]
![image](https://user-images.githubusercontent.com/79891120/114433797-3d3dfa80-9b90-11eb-92c6-1832487dab95.png)

**Comment by djose1164** [comment]
> ![image](https://user-images.githubusercontent.com/79891120/114433797-3d3dfa80-9b90-11eb-92c6-1832487dab95.png)

Estas corriendo una version desactualizada.

**Comment by djose1164** [comment]
> > Lo hago desde la rama de login. login-improved o desde ventas?
> 
> No, desde main. `git pull origin main --force`

Muestrame el output.

**Comment by djose1164** [comment]
> Le di a compilar y me siguen saliendo los mismos errores y el color, parece que no se me actualizo bien

Ejecutaste los anteriores comandos?

**Comment by milv24** [comment]
> > Le di a compilar y me siguen saliendo los mismos errores y el color, parece que no se me actualizo bien
> 
> Ejecutaste los anteriores comandos?

Sip

**Comment by djose1164** [comment]
> > Ejecutaste los anteriores comandos?
> 
> Sip

Ejecutalo y dejame ver el ouput `git pull origin main --force`

**Comment by milv24** [comment]
![image](https://user-images.githubusercontent.com/79891120/114440579-4fbc3200-9b98-11eb-943e-7105bcb02f21.png)

**Comment by djose1164** [comment]
> ![image](https://user-images.githubusercontent.com/79891120/114440579-4fbc3200-9b98-11eb-943e-7105bcb02f21.png)

No te habia salido merge conflict ni nada vdd?

**Comment by djose1164** [comment]
Muestrame la linea 178 de login.c

**Comment by milv24** [comment]
> > ![image](https://user-images.githubusercontent.com/79891120/114440579-4fbc3200-9b98-11eb-943e-7105bcb02f21.png)
> 
> No te habia salido merge conflict ni nada vdd?

Si, y acepte los incoming changes

**Comment by milv24** [comment]
![image](https://user-images.githubusercontent.com/79891120/114445260-dde6e700-9b9d-11eb-9b02-63aebe9ff416.png)
Estoy en una clase, por si ino te respondo tan rapido

**Comment by djose1164** [comment]
Ok, ahi ya veo ese error corregido. Tal vez ya este actualizado intenta copilar, y muestrame el output de `git log --oneline`

**Comment by djose1164** [comment]
Y `git tag -l`

**Comment by milv24** [comment]
> Ok, ahi ya veo ese error corregido. Tal vez ya este actualizado intenta copilar, y muestrame el output de `git log --oneline`

![image](https://user-images.githubusercontent.com/79891120/114484076-8d8c7b00-9bd7-11eb-83cc-92bd0f4de0ec.png)

**Comment by milv24** [comment]
> git tag -l

![image](https://user-images.githubusercontent.com/79891120/114484211-c6c4eb00-9bd7-11eb-9941-ba23e22329d0.png)

**Comment by djose1164** [comment]
Tu repo esta al dia. Debe ser alguna directiva que esta mal o algo.

**Comment by djose1164** [comment]
Intentaste copilar de nuevo?

**Comment by djose1164** [comment]
> Intentaste copilar de nuevo?

Antes ejecuta `git pull origin main`. Creo que ya deberia arreglarse.

**Comment by milv24** [comment]
> > Intentaste copilar de nuevo?
> 
> Antes ejecuta `git pull origin main`. Creo que ya deberia arreglarse.

Al parecer ya me compilo porque solo me aparecio PS C:\Users\privado\OneDrive\Documentos\Programacion en C Mecatronica PPM2021\Programacion-Modular>  en la terminal

**Comment by milv24** [comment]
Pero cuando lo ejecuto, se me queda parado ahi
![image](https://user-images.githubusercontent.com/79891120/114610560-0dfdbb00-9c6e-11eb-85ef-fdc2016ffbe1.png)

**Comment by djose1164** [comment]
> Pero cuando lo ejecuto, se me queda parado ahi
> ![image](https://user-images.githubusercontent.com/79891120/114610560-0dfdbb00-9c6e-11eb-85ef-fdc2016ffbe1.png)

Sip, justo esta manana repare ese bug. Eso solo pasaba en Windows debido al funcionamiento de getch(). Para mas contexto: https://stackoverflow.com/questions/473661/why-doesnt-pressing-enter-return-n-to-getch

**Comment by djose1164** [comment]
Actualiza tu repo (`git pull origin main`) e intenta copilar nuevamente. Si se soluciono recuerda cerrar el issue. Si se presenta otro bug, un nuevo issue para el.

**Comment by milv24** [comment]
> > Pero cuando lo ejecuto, se me queda parado ahi
> > ![image](https://user-images.githubusercontent.com/79891120/114610560-0dfdbb00-9c6e-11eb-85ef-fdc2016ffbe1.png)
> 
> Sip, justo esta manana repare ese bug. Eso solo pasaba en Windows debido al funcionamiento de getch(). Para mas contexto: https://stackoverflow.com/questions/473661/why-doesnt-pressing-enter-return-n-to-getch

Ok, pero entonces deberia cambiarlo, pero si ya lo arreglaste no..., aun me sigue saliendo el mismo bug

**Comment by djose1164** [comment]
> Ok, pero entonces deberia cambiarlo, pero si ya lo arreglaste no..., aun me sigue saliendo el mismo bug

Sip, los cambios estan en remoto ciertamente.
![image](https://user-images.githubusercontent.com/66039549/114618799-c9771d00-9c77-11eb-9811-e3da6a16f9b0.png)

**Comment by djose1164** [comment]
Ejecuta `git pull origin main --force` y luego ejecuta `git log --oneline` Si no ves el commit de _Fixes login on Windows._ bobo xD

**Comment by djose1164** [comment]
![image](https://user-images.githubusercontent.com/66039549/114619852-f677ff80-9c78-11eb-8008-11e344b87302.png)
Estoy desde Windows y me corre perfectamente.

**Comment by milv24** [comment]
![image](https://user-images.githubusercontent.com/79891120/114625616-853c4a80-9c80-11eb-824b-b5fa2db81887.png)
Si salio, ahora que procede?

**Comment by milv24** [comment]
> ![image](https://user-images.githubusercontent.com/66039549/114619852-f677ff80-9c78-11eb-8008-11e344b87302.png)
> Estoy desde Windows y me corre perfectamente.

Ah wey :(

**Comment by djose1164** [comment]
> ![image](https://user-images.githubusercontent.com/79891120/114625616-853c4a80-9c80-11eb-824b-b5fa2db81887.png)
> Si salio, ahora que procede?

Copilar y orar para que funcione :,v

**Comment by milv24** [comment]
> > ![image](https://user-images.githubusercontent.com/79891120/114625616-853c4a80-9c80-11eb-824b-b5fa2db81887.png)
> > Si salio, ahora que procede?
> 
> Copilar y orar para que funcione :,v

Sigue sin funcionar, sale el mismo bug 👎

**Comment by djose1164** [comment]
Pero presionaste enter y todo verdad? Muestrame la definicion q tenes en login.c de set_password

**Comment by djose1164** [comment]
> Pero presionaste enter y todo verdad? Muestrame la definicion q tenes en login.c de set_password

Ya vi tu rama. La funcion esta bien y todo. Hmm, que pasa cuando das enter dos veces? Nada?
