### ISSUE TITLE
Funciones Ventas

### ISSUE THREAD

**Issue by milv24** [djose1164/Programacion-Modular#18]
![image](https://user-images.githubusercontent.com/79891120/114293267-ae7f8f80-9a62-11eb-93a7-d1fbe23f0f44.png)
- get_usarname - Imprime el usuario que esta logeado
- get_product(id)- para introducir el codigo del producto y sale el nombre (creo que era algo asi xD)
- get_cantidad- esa solo es para ingresar la cantidad que se va a vender del producto( creo que eso podria ser una variable, no?
- get_precio_by_id- a partir del id se pone el precio creo que era
- edit_availableQuantity- esta edita el inventario, le resta los productos a vender @djose1164 @milv24

**Comment by djose1164** [comment]
`get_username()` Deberia ser una funcion de login. Como el programa solo acepta un usuario por ejecucion de servicio seria facil, simplemente cuando el usario se registre o se logue, `get_username()` devolveria la dirrecion de memoria.

**Comment by djose1164** [comment]
`get_product(id)` lo cambiaremos a `get_product_name(id)`. Asi ya uno sabe lo que hace xD. Y estaria en inventario.

**Comment by djose1164** [comment]
> * get_cantidad- esa solo es para ingresar la cantidad que se va a vender del producto( creo que eso podria ser una variable, no?
Sip, una variable de tu modulo. Esa funcion desde tu modulo deberia pedir por ese input.

**Comment by djose1164** [comment]
> * get_precio_by_id- a partir del id se pone el precio creo que era
Sip, deberia devolver el precio del producto

> * edit_availableQuantity- esta edita el inventario, le resta los productos a vender @djose1164 @milv24
Ok, esta tmb va en inventario.

**Comment by milv24** [comment]
Ok, entonces salen de inventario la de get_product_name(id),get_precio_by_id- y edit_availableQuantity-?

**Comment by milv24** [comment]
Otra cosa, tendria que agregar una funcion a login o ya hay una?

**Comment by djose1164** [comment]
> Ok, entonces salen de inventario la de get_product_name(id),get_precio_by_id- y edit_availableQuantity-?

Sip. Deberias crear un issue por cada una. Cuando esten listas yo simplemente cerraria el issue.

**Comment by djose1164** [comment]
> Otra cosa, tendria que agregar una funcion a login o ya hay una?

Nop, no lo hay. Otro issue para esa funcion igual.
