### ISSUE TITLE
Me esta dando estos conflictos para hacer merge pull request.

### ISSUE THREAD

**Issue by milv24** [djose1164/Programacion-Modular#24]
![image](https://user-images.githubusercontent.com/79891120/114333456-51451600-9b16-11eb-937a-e4412ae0068c.png)
![image](https://user-images.githubusercontent.com/79891120/114333498-6b7ef400-9b16-11eb-8748-c4ec5b3e2b96.png)

![image](https://user-images.githubusercontent.com/79891120/114333472-5bffab00-9b16-11eb-9e8a-69ea9b388cee.png)

**Comment by djose1164** [comment]
@milv24 Ya los resolvi. Busca en google como resolver conflictos de merge desde GitHub, o intenta hacerlo desde VSCode.
