### ISSUE TITLE
Modificar cuentas.

### ISSUE THREAD

**Issue by djose1164** [djose1164/Programacion-Modular#38]
@robert1090 Veo, y aun te falta la funcion de modificar cuentas. No veo nada q haga algo parecido.

**Comment by robert1090** [comment]
Es que es un registro, tenia entendido que no se tenia que modificar, solo llevar las cuentas

**Comment by djose1164** [comment]
Como esta en el mandato habra que anadirselo.

**Comment by robert1090** [comment]
Y como deberia de agregarlo? Digo, de donde salen los registros ya tienen un origen y estaria interfiriendo con ventas y compras

**Comment by djose1164** [comment]
Postea un issue asignandolo a Engeers y Milvia, donde le pedirias una funcion que duelva un punto a sus estructuras. Asi lo modificarias.
